### ISSUE TITLE
Errors when running composer install: Unable to add newly converted phar task_linux_amd64.tar

### ISSUE THREAD

**Issue by beto-aveiga** [Lullabot/drainpipe#135]
I'm trying to run functional tests.
When I run the "Build Project" step, on the first line that runs `composer install`, it fails.
Do you know what is happening?
Thanks!

---
`composer [install] failed, composer command failed: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-abc-exampleorg-website docker-compose -f /home/runner/work/abc-example.org-website/abc-example.org-website/.ddev/.ddev-docker-compose-full.yaml exec -w /var/www/html/drupal -T web composer install', action='[exec -w /var/www/html/drupal -T web composer install]', err='exit status 1', stdout='Gathering patches for root package.`

---
`In BinaryInstaller.php line 214:`
`Unable to add newly converted phar "/var/www/html/.ddev/.drainpipe-composer-cache/files/lullabot/drainpipe/bin/task/3.9.0/task_linux_amd64.tar" to the list of phars, a phar with that name already exists`

![image](https://user-images.githubusercontent.com/3916979/198123474-b70757d1-3ade-4a0f-8296-7e7db044fddb.png)

### Workflow code

````
name: "Functional Tests"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Functional-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.ddev/.drainpipe-composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: ./.github/actions/drainpipe/set-env

      - name: Install and Start DDEV
        uses: ./.github/actions/drainpipe/ddev
        with:
          git-name: Drainpipe Bot
          git-email: no-reply@example.com
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Build Project
        run: |
          composer install --no-interaction --quiet
          echo "PANTHEON_TOKEN=${{ secrets.PANTHEON_TERMINUS_TOKEN }}" > .env
          ddev task build:ci:functional

````
