### ISSUE TITLE
Improve support for switching between dev and production composer builds

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#169]
In my mind, one of the biggest benefit of `task` is that it allows us to express:

1. How to determine if source files have changed, and therefore a command needs to be re-run.
2. Dependencies that can be run in parallel, and those that need to be run in serial.

As is, the current `drupal:update` task has no dependency on composer. Ideally, if composer.json or composer.lock has changed, this task will run composer install automatically: https://github.com/Lullabot/drainpipe/blob/main/tasks/drupal.yml#L56-L58

We've replaced a few tasks in our site-specific Taskfile that I've included below. As well, by consolidating to a single command for `composer install` for both prod and dev installs, it allows parent tasks to depend on a single task and set the environment variable if needed.

What do others think about an approach like this? If it looks good, I can file a PR (but probably after the holidays).

cc @hawkeyetwolf

```yaml
  # Override Drainpipe's drupal:composer and drupal:update tasks until they
  # are changed upstream.
  #
  # The drupal:update command has no dependency on composer jobs. There's two
  # cases where we need composer to be run:
  #  1. Where composer hasn't been run at all.
  #  2. Where an environment is changing the "no-dev" flag for composer install.
  #
  # Since composer already has an environment variable to use, we use that
  # instead of having separate jobs. This allows drupal:update to depend on a
  # single composer task definition.
  override:drupal:composer:
    desc: Install composer dependencies
    summary: |
      This command is typically used when a developer updates their local after
      pulling new changes from source control. Generally when bootstrapping a
      fresh clone of the site from git, you'll need to run `composer install`
      anyway to get task and drainpipe.
    cmds:
      - |
        # We use the COMPOSER_NO_DEV environment variable to control production
        # builds.
        # https://getcomposer.org/doc/03-cli.md#composer-no-dev
        # We set it in case task is using the "alternate" syntax, including
        # when we call task via `ddev task`.
        export COMPOSER_NO_DEV={{.COMPOSER_NO_DEV}}
        composer install --optimize-autoloader
    sources:
      - composer.json
      - composer.lock
    generates:
      - ./vendor/composer/installed.json
      - ./vendor/autoload.php
    status:
      - >
        {{if eq .COMPOSER_NO_DEV "1"}}
        test -f ./vendor/composer/installed.json && grep -q '"dev": false' ./vendor/composer/installed.json
        {{else}}
        test -f ./vendor/composer/installed.json && grep -q '"dev": true' ./vendor/composer/installed.json
        {{end}}

  override:drupal:update:
    desc: Always run composer before updating.
    deps: [override:drupal:composer, drupal:update]

  build:
    desc: "Builds the project for production"
    cmds:
      - composer validate
      - task: override:drupal:composer
        vars:
          COMPOSER_NO_DEV: 1

  build:dev:
    desc: "Builds the project for development use"
    deps: [override:drupal:composer, assets:dev]
    cmds:
      # Task always calls dependencies in parallel. Since we need composer to
      # finish first, we run this in serial.
      # https://taskfile.dev/usage/#task-dependencies
      - task: override:drupal:update
      - ./vendor/bin/drush {{ .site }} -y en project_devel
```
