### ISSUE TITLE
Run cron once after Drupal update steps

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#190]
Some Drupal modules, like xmlsitemap, install a cron hook to build them. It's common to want to generate those once after pulling down a database or deploying to production.

Sites can do this with their local taskfile with something like this, but I think it's a common enough use case that it's worth doing by default.

```yaml
  override:drupal:update:
    desc: Always run composer before updating.
    deps: [drupal:update]
    cmds:
      # Run cron after updating to refresh items like the XML Sitemap.
      - ./vendor/bin/drush {{ .site }} cron
````
