### ISSUE TITLE
Add a yarn:install task and use it as a dependency

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drainpipe#192]
Even when yarn packages are up to date, it takes a few seconds to figure that out. We can fingerprint the yarn state to improve performance on builds. As well, yarn install outputs so much, so in this case we silenced it as well.

This example is from a project not using PNP, so there may be other work to do to make this task always return true for those projects. Perhaps it can use a status script instead of the generates files.

```yaml
  yarn:install:
    desc: "Installs packages with yarn"
    sources:
      - package.json
      - yarn.lock
    generates:
      - node_modules/.yarn-state.yml
    cmds:
      - echo "Running yarn install with output silenced..."
      - yarn install > /dev/null
```
