### ISSUE TITLE
DDEV is being reconfigured as php project type

### ISSUE THREAD

**Issue by justafish** [Lullabot/drainpipe#512]
```
name: site.com-d8
type: drupal10
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames:
    - '*.site.com-d8'
additional_fqdns: []
database:
    type: mariadb
    version: "10.4"
use_dns_when_possible: true
composer_version: "2"
web_environment:
    - NIGHTWATCH_DRUPAL_URL_CHROME=https://drupal_chrome
    - NIGHTWATCH_DRUPAL_URL_FIREFOX=https://drupal_firefox
hooks:
    post-start:
        - exec: ln -sf ../../scripts/githooks/pre-commit .git/hooks/pre-commit
        - exec: mysql -uroot -proot -hdb -e "CREATE DATABASE IF NOT EXISTS firefox; GRANT ALL ON firefox.* TO 'db'@'%';"
        - exec: mysql -uroot -proot -hdb -e "CREATE DATABASE IF NOT EXISTS chrome; GRANT ALL ON chrome.* TO 'db'@'%';"
nodejs_version: "16"
```

```
name: "Functional Tests"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Functional-Tests:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ddev/.drainpipe-composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: ./.github/actions/drainpipe/set-env

      - name: Install and Start DDEV
        uses: ./.github/actions/drainpipe/ddev
        with:
          git-name: Drainpipe Bot
          git-email: no-reply@example.com
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          #composer-cache-dir: false

      - name: Test DDEV Settings Generated
        run: test -f web/sites/default/settings.ddev.php
```

Uncommenting `composer-cache-dir:false` fixes it
