### ISSUE TITLE
Pantheon Update GitHub Action Syntax Error `syntax error near unexpected token `)'`

### ISSUE THREAD

**Issue by quicksketch** [Lullabot/drainpipe#601]
When running the `update` Pantheon action in GitHub Actions, I get a syntax error:

```
bash: -c: line 1: syntax error near unexpected token `)'
bash: -c: line 1: `set -eu && ( ./vendor/bin/task -l | grep '* update: '))'
Failed to execute command ./vendor/bin/task -l | grep '* update: '): exit status 2
```

![image](https://github.com/Lullabot/drainpipe/assets/100206/c5319cc4-e9b4-4809-87dc-785900d6bd5f)

This is the configuration of the action in my `PantheonDeployDev.yml` workflow:

```
      - name: Import config and run updates
        uses: ./.github/actions/drainpipe/pantheon/update
        with:
          site-name: ${{ vars.PANTHEON_SITE_NAME }}
          environment: dev
```

The syntax error is thrown on every deploy, but because it's part of an `if` (or `elif`) conditional, it simply returns as `false` and doesn't actually fail the entire workflow. PR to follow.
