### ISSUE TITLE
When adding Tugboat, also add drush.yml to generate drush uli ready links

### ISSUE THREAD

**Issue by beto-aveiga** [Lullabot/drainpipe#621]
We need a file `drush.yml` with:

```
options:
  uri: ${env.TUGBOAT_DEFAULT_SERVICE_URL_PROTOCOL}://${env.TUGBOAT_SERVICE_HOSTNAME}
```

And move it (could be in the online step)
```
      - cp "${TUGBOAT_ROOT}/.tugboat/drush.yml" "${TUGBOAT_ROOT}/drush"
```

So we can have ready login links in Tugboat.

Those changes can be included when Drainpipe manages Tugboat.

**Comment by mrdavidburns** [comment]
Based on our conversation during today's sync it was recommended that we do something similar to this which could be scaffold into our .tugboat/config.yml

https://docs.tugboatqa.com/starter-configs/code-snippets/terminal-aliases/

Do something like this in the `build` step.

```
- echo "export DRUSH_OPTIONS_URI=$TUGBOAT_DEFAULT_SERVICE_URL_PROTOCOL://$TUGBOAT_SERVICE_HOSTNAME"
```

This wouldn't required a lot of custom PHP code and be easier to maintain.
This wouldn't support multi-site, but this would cover a majority of our projects. We can figure out multi-site solution later after confirming this works.

**Comment by beto-aveiga** [comment]
I reviewed how we obtained the login link on a client, and I found that Drainpipe requires `vlucas/phpdotenv` which...

> Loads environment variables from .env to getenv(), $_ENV and $_SERVER automagically.

So, on this project, we create an `.env` file at `$TUGBOAT_ROOT`.
On that `.env` file we have the following content:
```
DRUSH_OPTIONS_URI=${TUGBOAT_DEFAULT_SERVICE_URL}
```
This will allow drush to work for single sites just as we need (with our drush commands and inside the Tugboat terminal)

Using `export` will be helpful only for subsequent scripts after that line, maybe during the build process, but not in the Tugboat terminal.

So, a suggestion is to find if there is an .env file at $TUGBOAT_ROOT, if not, create it. 
Like: `touch $TUGBOAT_ROOT/.env`

Then append this line: echo "DRUSH_OPTIONS_URI=${TUGBOAT_DEFAULT_SERVICE_URL}" >> "$TUGBOAT_ROOT/.env"

Does it sound right?

I will try this on a separate PR to see if it will work in a real Tugboat environment.

**Comment by beto-aveiga** [comment]
I also saw this solution on a Taskfile for another project:

![Image](https://github.com/user-attachments/assets/c8f9631e-78d5-4258-ab3c-b0ae0e459b50)

We could use similar logic. Looks simple too.

**Comment by mrdavidburns** [comment]
I'd rather not rely on anything in `.env` files for Tugboat because our most common way to handle that is by setting the Environment variables in the Tugboat Dashboard. This would make it more confusing IMO that we're now thinking about Environment Variables in multiple locations.

I think the Taskfile is an okay solution and would allow this to be overwritten if needed, like to support mutli-site.

**Comment by beto-aveiga** [comment]
Okay! I will do it in a Taskfile.

- I will add a `tugboat.yml` for inclusion in `Taskfile.yml`.
- When `tugboat.yml` gets included (manually by the user), a command like `tugboat:drush.uli:setup`  will be available.
- `tugboat:drush.uli:setup` can be included to run as part of `tugboat:online` or added manually to run into the build step in `.tugboat/config.yml`
- I will add documentation to let users know about this Task command.

I think that adding documentation is better than parsing `Taskfile.yml` and adding content to it automatically, plus adding documentation for a `composer.json` setting that triggers this automation. Does it sound right?

We can share with the user the responsibility of implementing a simple command (`tugboat:drush.uli:setup`) to have the login link for Drupal, which is easier for us to maintain.

@mrdavidburns

**Comment by mrdavidburns** [comment]
Discussed during sync.

Create a new taskfile specific for Tugboat (tugboat.yml)

This should get scaffold into new projects. We should add a warning for existing projects if they want to use these task commands.

Current example of taskfile that is generated for new projects. These lines get inserted at the top based on drainpipe configuration in composer.

```
includes:
  deploy: ./vendor/lullabot/drainpipe/tasks/deploy.yml
  drupal: ./vendor/lullabot/drainpipe/tasks/drupal.yml
  github: ./vendor/lullabot/drainpipe/tasks/github.yml
  sass: ./vendor/lullabot/drainpipe/tasks/sass.yml
  snapshot: ./vendor/lullabot/drainpipe/tasks/snapshot.yml
  javascript: ./vendor/lullabot/drainpipe/tasks/javascript.yml
  pantheon: ./vendor/lullabot/drainpipe/tasks/pantheon.yml
  test: ./vendor/lullabot/drainpipe/tasks/test.yml
````
